<a href="https://colab.research.google.com/github/AliSalman25/first-Jupyter-Notebook-for-the-experiments/blob/main/colab_first_paper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dataset

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

**Date Source** : OPEC formal website    
            https://www.opec.org/opec-basket-price.html

**Type of data** : OPEC Reference Basket (ORB)  
Period : 2003-01-02 to 2025-06-27

**Framing** :  Univariate

In [24]:
file_path = '/content/drive/MyDrive/Colab Notebooks/FirstPaperColabWork/Dataset.csv'
df = pd.read_csv(file_path)
df.head()

Empty DataFrame
Columns: [Date, Price]
Index: []

**Data Preparation**

Step 1:  Xml file Oil price data  downloaded from the official OPEC website , after that converted it to CSV in colab

In [27]:
import pandas as pd
import xml.etree.ElementTree as ET
from google.colab import drive

#  conn Google Drive
drive.mount('/content/drive')

#  path  XML
xml_file_path = '/content/drive/MyDrive/Colab Notebooks/FirstPaperColabWork/basketDayArchives.xml'

#  read XML
tree = ET.parse(xml_file_path)
root = tree.getroot()

# data and price from xml fil
dates = []
prices = []
for basket in root.findall('{http://tempuri.org/basketDayArchives.xsd}BasketList'):
    date = basket.attrib['data']
    price = float(basket.attrib['val'])
    dates.append(date)
    prices.append(price)

#  create DataFrame
df = pd.DataFrame({
    'Date': pd.to_datetime(dates),
    'Price': prices
})

#     save to CSV
csv_file_path = '/content/drive/MyDrive/Colab Notebooks/FirstPaperColabWork/Dataset.csv'
df.to_csv(csv_file_path, index=False)

#    read first 5 columns
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

        Date  Price
0 2003-01-02  30.05
1 2003-01-03  30.83
2 2003-01-06  30.71
3 2003-01-07  29.72
4 2003-01-08  28.86

**Data Preparation**

Step 2: Code for Exploratory Data Analysis (EDA)

- They display general information about the data, including the number of rows and columns.

- They check if there are any missing (null) values.

- They provide statistics about the Price column.

- They ensure that the Date column is stored correctly as a datetime type.

- They detect if there are any duplicate dates.

In [31]:
import pandas as pd

#  Read the CSV file
file_path = '/content/drive/MyDrive/Colab Notebooks/FirstPaperColabWork/Dataset.csv'
df = pd.read_csv(file_path)

#  Display general information about the data
print("Data shape (rows, columns):", df.shape)
print("\nGeneral information and missing data:")
print(df.info())

#  Display the first 5 rows
print("\nFirst 5 records:")
print(df.head())

#  Check  missing data in columns
print("\nNumber of missing values per column:")
print(df.isnull().sum())

#  Descriptive statistics for the 'Price' column
print("\nDescriptive statistics for the 'Price' column:")
print(df['Price'].describe())

#  Ensure 'Date' column is in datetime format
df['Date'] = pd.to_datetime(df['Date'])
print("\n'Date' column data type after conversion:")
print(df['Date'].dtype)

#  Check for duplicate dates (optional)
duplicates = df['Date'].duplicated().sum()
print(f"\nNumber of duplicated dates: {duplicates}")

Data shape (rows, columns): (5799, 2)

General information and missing data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5799 entries, 0 to 5798
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    5799 non-null   object
 1   Price   5799 non-null   float64
dtypes: float64(1), object(1)
memory usage: 90.7+ KB
None

First 5 records:
         Date  Price
0  2003-01-02  30.05
1  2003-01-03  30.83
2  2003-01-06  30.71
3  2003-01-07  29.72
4  2003-01-08  28.86

Number of missing values per column:
Date     0
Price    0
dtype: int64

Descriptive statistics for the 'Price' column:
count    5799.000000
mean       70.377513
std        25.693673
min        12.220000
25%        50.695000
50%        68.680000
75%        88.445000
max       140.730000
Name: Price, dtype: float64

'Date' column data type after conversion:
datetime64[ns]

Number of duplicated dates: 0